//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormBuilderModule.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FormBuilderModule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// AngularJS v1.2.23
        /// (c) 2010-2014 Google, Inc. http://angularjs.org
        /// License: MIT
        ///*/
        ///(function(Q,X,t){&apos;use strict&apos;;function x(b){return function(){var a=arguments[0],c,a=&quot;[&quot;+(b?b+&quot;:&quot;:&quot;&quot;)+a+&quot;] http://errors.angularjs.org/1.2.23/&quot;+(b?b+&quot;/&quot;:&quot;&quot;)+a;for(c=1;c&lt;arguments.length;c++)a=a+(1==c?&quot;?&quot;:&quot;&amp;&quot;)+&quot;p&quot;+(c-1)+&quot;=&quot;+encodeURIComponent(&quot;function&quot;==typeof arguments[c]?arguments[c].toString().replace(/ \{[\s\S]*$/,&quot;&quot;):&quot;undefined&quot;==typeof arguments[c]?&quot;undefined&quot;:&quot;string&quot;!=typeof arguments[c]?JSON.stringify(argum [rest of string was truncated]&quot;;.
        /// </summary>
        public static string app {
            get {
                return ResourceManager.GetString("app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;section class=&apos;fb-meta&apos;&gt;
        ///	&lt;div&gt;
        ///		&lt;label&gt;
        ///			&lt;span&gt;Name&lt;/span&gt;
        ///			&lt;input type=&apos;text&apos; ng-model=&quot;model.Name&quot; placeholder=&quot;Name&quot;/&gt;
        ///		&lt;/label&gt;
        ///	&lt;/div&gt;
        ///	&lt;div&gt;
        ///		&lt;label&gt;
        ///			&lt;span&gt;Description&lt;/span&gt;
        ///			&lt;input type=&apos;text&apos; ng-model=&quot;model.Description&quot; placeholder=&quot;Description&quot;/&gt;
        ///		&lt;/label&gt;
        ///	&lt;/div&gt;
        ///&lt;/section&gt;
        ///&lt;section class=&apos;sections&apos;&gt;
        ///	&lt;ul ui-sortable ng-model=&quot;model.Sections&quot;&gt;
        ///		&lt;li class=&apos;section-group&apos; ng-repeat=&quot;section in model.Sections&quot;&gt;
        ///			&lt;ul ui-sortable ng-model=&quot;model.Fields&quot;&gt;
        ///				&lt;li cl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Builder_template {
            get {
                return ResourceManager.GetString("Builder_template", resourceCulture);
            }
        }
    }
}
